GET http://assignment-10-server-tawny.vercel.app/api/products HTTP/1.1
content-type: application/json

{
    "name": "product 01",
    "price":69,
    "description": "this is very good product",
    "imageUrl":"https://res.cloudinary.com/dsuh9ww6d/image/upload/v1672897809/bike_d9fcb8.png"

}